
CREATE TABLE [dbo].[Alimentos$](
	[Group] [nvarchar](255) NULL,
	[Subgrupo] [nvarchar](255) NULL,
	[Sub-código] [nvarchar](255) NULL,
	[Nome] [nvarchar](255) NULL,
	[Energia (kcal)] [float] NULL,
	[Energia (kJ)] [float] NULL,
	[Água (g)] [float] NULL,
	[Proteína (g)] [float] NULL,
	[Fibra alimentar (g)] [float] NULL,
	[Colesterol (mg)] [float] NULL,
	[Álcool (g)] [float] NULL,
	[Amido (g)] [float] NULL,
	[Gordura total (g)] [float] NULL,
	[Total HC disponíveis (g)] [float] NULL,
	[Total HC expresso em monossacáridos (g)] [float] NULL,
	[Oligossacáridos (g)] [float] NULL,
	[Mono + dissacáridos (g)] [float] NULL,
	[Ácidos orgânicos (g)] [float] NULL,
	[Ácidos gordos saturados (g)] [float] NULL,
	[Ácidos gordos monoinsaturados (g)] [float] NULL,
	[Ácidos gordos polinsaturados  (g)] [float] NULL,
	[Ácidos gordos trans (g)] [float] NULL,
	[Ácido linoleico (g)] [float] NULL,
	[Retinol (vit# A total) (mg)] [float] NULL,
	[Vit A total (equivalentes retinol) (mg)] [float] NULL,
	[Caroteno (mg)] [float] NULL,
	[vit# D (µg)] [float] NULL,
	[a-tocoferol (mg)] [float] NULL,
	[Tiamina (mg)] [float] NULL,
	[Riboflavina (mg)] [float] NULL,
	[Equivalentes de niacina (mg)] [float] NULL,
	[Niacina (mg)] [float] NULL,
	[Triptofano/60 (mg)] [float] NULL,
	[vit B6 (mg)] [float] NULL,
	[Vit# B12 (µg)] [float] NULL,
	[vit# C (mg)] [float] NULL,
	[Folatos (µg)] [float] NULL,
	[Cinza (g)] [float] NULL,
	[Na (mg)] [float] NULL,
	[K    (mg)] [float] NULL,
	[Ca (mg)] [float] NULL,
	[P (mg)] [float] NULL,
	[Mg (mg)] [float] NULL,
	[Fe (mg)] [float] NULL,
	[Zn (mg)] [float] NULL
) ON [PRIMARY]

GO


