
CREATE TABLE [dbo].[UserBreastFeeding]
(
	[Id] BIGINT NOT NULL IDENTITY,
	[UserId] BIGINT NOT NULL,
	[StartDate] DATE NOT NULL,
	[EndDate] DATE NULL,

	CONSTRAINT PK_UserBreastFeeding PRIMARY KEY([Id]),
	
	CONSTRAINT FK_UserBreastFeeding_User 
		FOREIGN KEY(UserId) REFERENCES [User](UserId)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)

